version: '3.1'

services:
  db:
    image: postgres:16-alpine
    container_name: postgres16-bd
    restart: always
    environment:
      POSTGRES_USER: criciumenses
      POSTGRES_PASSWORD: CriciumaNaSerieA
      POSTGRES_DB: employeeManagement
    ports:
      - "7654:5432"
    volumes:
      - my_dbdata:/var/lib/postgresql/data

volumes:
  my_dbdata:

